Bump com.google.truth:truth from 1.1.3 to 1.4.4 (#11)
Bumps [com.google.truth:truth](https://github.com/google/truth) from
1.1.3 to 1.4.4.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/google/truth/releases">com.google.truth:truth's
releases</a>.</em></p>
<blockquote>
<h2>v1.4.4</h2>
<ul>
<li>Annotated the rest of the main package for nullness, and moved the
<code>@NullMarked</code> annotation from individual classes up to the
package to avoid <a
href="https://redirect.github.com/google/truth/issues/1320">a warning
under <code>--release 8</code></a>. (e107aeadc)</li>
<li>Improved the failure message for <code>matches</code> to
conditionally suggest using <code>containsMatch</code>. (7e9fc7aec)</li>
</ul>
<h2>1.4.3</h2>
<p><strong>Known Issue for at least some builds targeting Java 8, fixed
in <a
href="https://github.com/google/truth/releases/tag/v1.4.4">1.4.4</a>:</strong>
&quot;unknown enum constant ElementType.MODULE&quot;: <a
href="https://redirect.github.com/google/truth/issues/1320">google/truth#1320</a>.
As far as we know, this is only a warning, so it should cause practical
problems only if you use <code>-Werror</code> or you perform reflection
on <a
href="https://jspecify.dev/docs/api/org/jspecify/annotations/NullMarked.html"><code>@NullMarked</code></a>
under a Java 8 runtime.</p>
<ul>
<li>Added more nullness information to our APIs (in the form of <a
href="https://jspecify.dev/">JSpecify</a> annotations). This could lead
to additional warnings (or even errors) for users of Kotlin and other
nullness checkers. Please <a
href="https://github.com/google/truth/issues/new">report any
problems</a>. (ee680cbaf)</li>
<li>Deprecated <code>Subject.Factory</code> methods for Java 8 types. We
won't remove them, but you can simplify your code by migrating off them:
Just replace <code>assertAbout(foos()).that(foo)</code> with
<code>assertThat(foo)</code> (or <code>about(foos()).that(foo)</code>
with <code>that(foo)</code>). (59e7a5065)</li>
</ul>
<h2>1.4.2</h2>
<p>This release is the final step of copying all our methods from
<code>Truth8</code> to <code>Truth</code>. If you have not already
migrated your usages from <code>Truth8</code> to <code>Truth</code>, you
may see build errors:</p>
<pre><code>OptionalSubjectTest.java:39: error: reference to assertThat
is ambiguous
    assertThat(Optional.of(&quot;foo&quot;)).isPresent();
    ^
both method
assertThat(@org.checkerframework.checker.nullness.qual.Nullable
Optional&lt;?&gt;) in Truth8 and method
assertThat(@org.checkerframework.checker.nullness.qual.Nullable
Optional&lt;?&gt;) in Truth match
</code></pre>
<p>In most cases, you can migrate your whole project mechanically:
<code>git grep -l Truth8 | xargs perl -pi -e
's/\bTruth8\b/Truth/g;'</code>. (You can make that change before
upgrading to Truth 1.4.2 or as part of the same commit.)</p>
<p>If you instead need to migrate your project incrementally (for
example, because it is very large), you may want to upgrade your version
of Truth incrementally, too, following our instructions for <a
href="https://github.com/google/truth/releases/tag/v1.3.0">1.3.0</a> and
<a
href="https://github.com/google/truth/releases/tag/v1.4.0">1.4.0</a>.</p>
<h2>For help</h2>
<p>Please feel welcome to <a
href="https://github.com/google/truth/issues/new">open an issue</a> to
report problems or request help.</p>
<h2>Changelog</h2>
<ul>
<li>Removed temporary type parameters from
<code>Truth.assertThat(Stream)</code> and
<code>Truth.assertThat(Optional)</code>. This can create build errors,
which you can fix by replacing all your references to
<code>Truth8</code> with references to <code>Truth</code>.
(45782bd0e)</li>
</ul>
<h2>1.4.1</h2>
<p>This release deprecates <code>Truth8</code>.</p>
<p>All its methods have become available on the main <code>Truth</code>
class. In most cases, you can migrate your whole project mechanically:
<code>git grep -l Truth8 | xargs perl -pi -e
's/\bTruth8\b/Truth/g;'</code></p>
<p>While we do not plan to delete <code>Truth8</code>, we recommend
migrating off it, at least if you static import <code>assertThat</code>:
If you do not migrate, such static imports will become ambiguous in
Truth 1.4.2, breaking your build.</p>
<h2>1.4.0</h2>
<p>In this release, our assertions on Java 8 types continue to move from
the <code>Truth8</code> class to the main <code>Truth</code> class. This
change should not break compatibility for any supported JDK or Android
version, even users who test under old versions of Android without <a
href="https://developer.android.com/studio/write/java8-support#library-desugaring">API
desugaring</a>. Additionally, we will never break binary compatibility,
though some users will have to make changes to their source code in
order for it to compile against newer versions.</p>
<p>This release is likely to lead to more <strong>build
failures</strong> than <a
href="https://github.com/google/truth/releases/tag/v1.3.0">1.3.0</a>
did. However, those failures should be <strong>straightforward to
fix</strong>.</p>
<h2>Example build failure</h2>
<pre><code>Foo.java:152: error: reference to assertThat is ambiguous
    assertThat(repo.findFileWithName(&quot;foo&quot;)).isNull();
&lt;/tr&gt;&lt;/table&gt; 
</code></pre>
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li>See full diff in <a
href="https://github.com/google/truth/commits/v1.4.4">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=com.google.truth:truth&package-manager=gradle&previous-version=1.1.3&new-version=1.4.4)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>